#pragma once

#include "TreeNode.hpp"
#include "Program.hpp"
#include "MainClass.hpp"
#include "ClassStorage.hpp"

#include "Expression.hpp"
#include "AddExpression.hpp"
#include "AndExpression.hpp"
#include "BoolExpression.hpp"
#include "DivExpression.hpp"
#include "GreaterEqualExpression.hpp"
#include "GreaterExpression.hpp"
#include "IdentExpression.hpp"
#include "IntExpression.hpp"
#include "LessEqualExpression.hpp"
#include "LessExpression.hpp"
#include "MulExpression.hpp"
#include "NotExpression.hpp"
#include "OrExpression.hpp"
#include "SubExpression.hpp"
#include "ModExpression.hpp"
#include "EqualExpression.hpp"
#include "ArrayAccessExpression.hpp"
#include "NewArrayExpression.hpp"

#include "Declaration.hpp"
#include "DeclarationList.hpp"
#include "VariableDeclaration.hpp"
#include "MethodDeclaration.hpp"
#include "ClassDeclaration.hpp"
#include "ClassDeclarationList.hpp"
#include "Formal.hpp"
#include "FormalList.hpp"

#include "Statement.hpp"
#include "StatementList.hpp"
#include "AssignmentStatement.hpp"
#include "IfStatement.hpp"
#include "PrintStatement.hpp"
#include "ReturnStatement.hpp"
#include "VariableDeclarationStatement.hpp"
#include "WhileStatement.hpp"
#include "AssertStatement.hpp"
#include "IfElseStatement.hpp"
#include "ScopeStatement.hpp"

#include "NamedEntity.hpp"
#include "NamedVariable.hpp"
#include "NamedArrayElement.hpp"

#include "Type.hpp"
#include "SimpleType.hpp"
#include "ArrayType.hpp"

#include "InterpreterValues/Value.hpp"
#include "InterpreterValues/IntValue.hpp"
#include "InterpreterValues/BoolValue.hpp"

#include "Symbol.hpp"
#include "ScopeLayer.hpp"
#include "ScopeLayerTree.hpp"